[tool.poetry]
name = "fastapi-tutorial"
version = "0.1.0"
description = ""
authors = ["jaewon"]
readme = "README.md"
packages = [{include = "fastapi_tutorial"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
